name: deploy

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          cargo install cargo-make
          cargo make build

      - name: Copy result
        run: |
          mkdir ./public
          cp -r ./pkg ./public/
          cp ./index.html ./public/
          rm -f ./public/pkg/.gitignore

      - name: Check
        run: |
          ls -al ./public
          ls -al ./public/pkg

      - name: Publish generated content to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: public
